name: Validate & Badge Milestones

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    paths:
      - "milestones/**"
      - ".github/schema/**"
      - "scripts/**"

jobs:
  validate:
    name: "1️⃣ Validate milestones.json"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python for validation
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install jsonschema
        run: pip install jsonschema

      - name: Run JSON schema validation
        run: |
          python - <<PYCODE
          import json, jsonschema
          schema = json.load(open(".github/schema/milestones.schema.json"))
          data   = json.load(open("milestones/milestones.json"))
          jsonschema.validate(instance=data, schema=schema)
          print("✅ milestones.json is valid")
          PYCODE

  badges:
    name: "2️⃣ Generate SVG badges"
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: false

      - name: Set up runtime
        run: |
          if [ -f scripts/generateBadge.py ]; then
            echo "⏳ Using Python badge generator"
            python3 -m pip install --upgrade pip
            pip install pybadges
          else
            echo "⏳ Using Node badge generator"
            curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs
          fi

      - name: Generate badges
        run: |
          if [ -f scripts/generateBadge.py ]; then
            python3 scripts/generateBadge.py
          else
            node scripts/generate-badges.js
          fi

      - name: Pull latest changes
        run: |
          git config user.name "GhostOps Bot"
          git config user.email "noreply@github.com"
          git pull origin main --rebase

      - name: Commit badges
        uses: EndBug/add-and-commit@v9
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          author_name: "GhostOps Bot"
          author_email: "noreply@github.com"
          message: "chore: update milestone badges"
          add: "badges/*.svg"
