name: Validate & Badge Milestones

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    paths:
      - "milestones/**"
      - ".github/schema/**"
      - "scripts/**"

jobs:
  validate:
    name: "1️⃣ Validate milestones.json"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install jsonschema
        run: pip install jsonschema

      - name: Validate JSON
        run: |
          python - <<PYCODE
          import json, jsonschema
          schema = json.load(open(".github/schema/milestones.schema.json"))
          data   = json.load(open("milestones/milestones.json"))
          jsonschema.validate(instance=data, schema=schema)
          print("✅ milestones.json is valid")
          PYCODE

  badges:
    name: "2️⃣ Generate SVG badges"
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install pybadges
        run: pip install pybadges

      - name: Generate badges
        run: python scripts/generateBadge.py

      - name: Commit badges
        uses: EndBug/add-and-commit@v9
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          author_name: "GhostOps Bot"
          author_email: "noreply@github.com"
          message: "chore: update milestone badges"
          add: "badges/*.svg"
